[package]
name = "flappy-square"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
raylib = "3.7.0"
raylib-sys = "3.7.0"
